services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
      network: host
    ports:
      - 8080:${PORT}
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT_INNER}
      DATABASE_URL: postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT_INNER}/${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT_INNER}
      AUTH_TOKEN_TTL: ${AUTH_TOKEN_TTL}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    depends_on:
      - postgres
      - redis
      - jaeger

  postgres:
    image: postgres:17
    ports:
      - ${DATABASE_PORT_OUTER}:${DATABASE_PORT_INNER}
    volumes:
      - db:/var/lib/postgres/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT_OUTER}:${REDIS_PORT_INNER}

  jaeger:
    image: jaegertracing/jaeger:2.21.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

volumes:
  db:
