[package]
name = "adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
bcrypt.workspace = true
derive-new.workspace = true
redis.workspace = true
sqlx.workspace = true

kernel.workspace = true
shared.workspace = true

[dev-dependencies]
anyhow.workspace = true
tokio.workspace = true
