[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
axum-extra.workspace = true
derive-new.workspace = true
garde.workspace = true
serde.workspace = true
strum.workspace = true
utoipa.workspace = true

kernel.workspace = true
registry.workspace = true
shared.workspace = true
